disabled = false
languageCode = "fr"
languageName = "Français"
weight = 1

[params]
displayName = "FR"
isoCode = "fr"
rtl = false
dateFormat = "2 Janvier 2006"
logo = "img/logo/light_mode.png"

["params.author"]
name = "La Minute Cyber"
