[[main]]
name = "Accueil"
pageRef = "index"
weight = 1

[[main]]
name = "News"
pageRef = "news"
weight = 2

[[main]]
name = "Vulnérabilités"
pageRef = "vulnerabilités"
weight = 3

[[main]]
name = "Attaques"
pageRef = "attaques"
weight = 4

[[main]]
name = "Histoires"
pageRef = "histoires"
weight = 5

# [[main]]
# name = "Recaps"
# pageRef = "recaps"
# weight = 6

[[main]]
pre = "github"
url = "https://github.com/La-Minute-Cyber/laminutecyber"
weight = 30


[[footer]]
none = "none"
